/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./components/Card.vue')['default']
    GameCard: typeof import('./components/GameCard.vue')['default']
    GameMergeDialog: typeof import('./components/GameMergeDialog.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SakuraEffect: typeof import('./components/SakuraEffect.vue')['default']
    SakuraTree: typeof import('./components/SakuraTree.vue')['default']
    TagList: typeof import('./components/TagList.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheSidebar: typeof import('./components/TheSidebar.vue')['default']
    Upload: typeof import('./components/Upload.vue')['default']
  }
}
